version: "3"

services:
  app:
    environment:
      TZ: "Asia/Jakarta"
    build:
      context: Back-End
    ports:
      - "5000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    restart: always